name: issue_comment_created

on:
  issue_comment:
    types: [created]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: run
      env:
        IC_BODY: ${{ github.event.comment.body }}
        IC_URL: ${{ github.event.comment.html_url }}
      run: |
        echo $IC_BODY
        echo $IC_URL
