name: CI

on:
  issue_comment:
    types: [created]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      env:
        GITHUB_EVENT: ${{ toJson(github.event) }}
      run: echo $GITHUB_EVENT
